#!/usr/bin/with-contenv bash

echo "**** checking playback duration ****"

card=$(cat /etc/asound.conf |grep pcm|cut -d' ' -f2)
status_path=$(find /proc/asound/card${card:-0} -type f -name status|head -n1)
if [ ! "$status_path" ]; then
    echo "Couldn't find status file in /proc/asound/card${card:-0}. Check if asound.conf is configured"
    exit 1
fi

max_diff=$((${MAX_PLAYBACK_DURATION:-60}*60))
while true
do
    output="$(cat $status_path)"
    start="$(echo "$output"|grep trigger_time|cut -d: -f2|cut -d. -f1)"
    now="$(echo "$output"|grep tstamp|cut -d: -f2|cut -d. -f1)"
    diff=$((now - start))

    echo "**** Stream was playing for $diff sec ****"
    echo "$output"

    if [ "$diff" -gt "$max_diff" ]; then
        echo "Restarting plexamp.."
        s6-svc -r /run/service/plexamp
    fi
    sleep 300
done