#!/usr/bin/with-contenv bash

echo "**** checking playback duration ****"

card=$(cat /etc/asound.conf|grep pcm|cut -d' ' -f2)
status_path=$(find /proc/asound/card${card:-0} -type f -name status|head -n1)
if [ ! "$status_path" ]; then
    echo "Couldn't find status file in /proc/asound/card${card:-0}. Check if asound.conf is configured and systempaths=unconfined is set."
    exit 1
fi

max_duration=$((${MAX_PLAYBACK_DURATION:-60}*60))
while true
do
    output="$(cat $status_path)"
    start="$(echo "$output"|grep trigger_time|cut -d: -f2|cut -d. -f1)"
    now="$(echo "$output"|grep tstamp|cut -d: -f2|cut -d. -f1)"
    duration=$((now - start))
    pid=$(echo "$output" | grep owner_pid | cut -d: -f2)

    if [ "$pid" ]; then
        echo "**** Stream (pid=$pid) was playing for ${diff}s ****"
    else
        echo "**** No active alsa streams ****"
    fi

    if [ "$duration" -gt "$max_duration" ]; then
        echo "Playback exceeded max playback duration (${MAX_PLAYBACK_DURATION}m). Restarting music services.."
        s6-svc -r /run/service/plexamp
        s6-svc -r /run/service/spotifyd
    fi
    sleep 300
done