#!/usr/bin/with-contenv bash

err=""

if [ ! "$(find /plexamp-data/.local/share/Plexamp/Settings -type f -name *uuid*)" 
		&& ! "$PLEXAMP_CLAIM_TOKEN" ]; then
	err=$err"PLEXAMP_CLAIM_TOKEN"
fi

if [ ! "$DEVICE_NAME1" ]; then
	err=$err"DEVICE_NAME"
fi

if [ "$err" ]; then
	echo "Missing env variable(s): $err"
	# this doesnt set the exit code of the container for some reason..
	# echo "1" > /run/s6-linux-init-container-results/exitcode 
	/run/s6/basedir/bin/halt
	exit 1
fi

# usermod -a -G audio abc
# chown -R abc:abc /plexamp-data

# set alsa volume
# amixer set Master 90% || echo