name: Check Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v3
    - name: Check Deps
      run: |
        USER_IMAGE=linuxserver/baseimage-debian
        
        plexampVersion=$(curl -s "https://plexamp.plex.tv/headless/version.json" | jq -r '.latestVersion')
        [ "$?" -ne "0" ] && exit 1
        spotifydVersion=$(curl -s "https://api.github.com/repos/Spotifyd/spotifyd/releases/latest" | jq -r '.tag_name')
        [ "$?" -ne "0" ] && exit 2
        token=$(curl -s "https://ghcr.io/token?scope=repository:${USER_IMAGE}:pull" | jq -r '.token')
        baseimageHash=$(curl -s -H "Authorization: Bearer $token" "https://ghcr.io/v2/${USER_IMAGE}/manifests/amd64-bookworm" | jq -r '.config.digest')
        [ "$?" -ne "0" ] && exit 3

        echo "$plexampVersion|$spotifydVersion|$baseimageHash" 
        jq -n --arg plexampVersion "$plexampVersion" --arg spotifydVersion "$spotifydVersion" --arg baseimageHash "$baseimageHash" \
          '{
            plexampVersion: $ARGS.plexampVersion, 
            spotifydVersion: $ARGS.spotifydVersion, 
            baseimageHash: $ARGS.baseimageHash
            }' > versions.json
        git add .
        git commit -m "Version updates" .
        git push
