name: Check Dependency Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  check-updates:
    runs-on: ubuntu-latest
    outputs:
      out-of-date: ${{ steps.check-updates.outputs.out-of-date }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Check Updates
      id: check-updates
      run: |
        USER_IMAGE=linuxserver/baseimage-debian
        
        plexampVersion=$(curl -s "https://plexamp.plex.tv/headless/version.json" | jq -r '.latestVersion')
        [ "$?" -ne "0" ] && exit 1
        spotifydVersion=$(curl -s "https://api.github.com/repos/Spotifyd/spotifyd/releases/latest" | jq -r '.tag_name')
        [ "$?" -ne "0" ] && exit 2
        token=$(curl -s "https://ghcr.io/token?scope=repository:${USER_IMAGE}:pull" | jq -r '.token')
        baseimageHash=$(curl -s -H "Authorization: Bearer $token" "https://ghcr.io/v2/${USER_IMAGE}/manifests/amd64-bookworm" | jq -r '.config.digest')
        [ "$?" -ne "0" ] && exit 3

        echo "$plexampVersion|$spotifydVersion|$baseimageHash" 
        jq -n --arg plexampVersion "$plexampVersion" \
          --arg spotifydVersion "$spotifydVersion" \
          --arg baseimageHash "$baseimageHash" \
          '$ARGS.named' > versions.json

        # check if anything changed
        if [[ `git status --porcelain` ]]; then
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add versions.json
          git commit -m "Version updates" .
          git push
          # pushes by github-actions[bot] wont trigger subsequent builds as per https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
          # so we do it explicitly
          echo "out-of-date=true" >> "$GITHUB_OUTPUT"
        fi
    
  build-docker-image:
    permissions:
      contents: read
      packages: write
    if: needs.check-updates.out-of-date == 'true'
    needs: [check-updates]
    uses: parttimer777/docker-hifistreamer/.github/workflows/docker-image.yml@main
